version: '3.4'

services:
  nellebot:
    build:
      context: ..
      dockerfile: docker-dev/Dockerfile
      no_cache: true
    environment:
      - DOTNET_ENVIRONMENT=Development
    env_file: .env.local
    volumes:
      - nellebot-keydata:/keydata
      - ${USERPROFILE}/.nellebot-certs:/certs:ro
    depends_on:
      - nellebot-pgsql

  nellebot-pgsql:
    image: postgres:15.5
    ports:
      - "5533:5432"
    environment:
      POSTGRES_USER: nellebot
      POSTGRES_PASSWORD: hunter2
      POSTGRES_DB: nellebot-dev
    volumes:
      - nellebot-pgdata:/var/lib/postgresql/data

  nellebot-pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5544:80"
    profiles:
      - tools
    depends_on:
      - nellebot-pgsql
    environment:
      PGADMIN_DEFAULT_EMAIL: nelle@bot.local
      PGADMIN_DEFAULT_PASSWORD: hunter2

volumes:
  nellebot-keydata:
    driver: local
  nellebot-pgdata:
    driver: local