version: '3.4'

services:
  nellebot:
    build:
      context: ..
      dockerfile: Nellebot/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - nellebot-keydata:/keydata
      - ${USERPROFILE}/.certs:/home/app/.certs
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    depends_on:
      - nellebot-pgsql

  nellebot-pgsql:
    image: postgres:15.5
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: nellebot
      POSTGRES_PASSWORD: hunter2
      POSTGRES_DB: nellebot-dev
    volumes:
      - nellebot-pgdata:/var/lib/postgresql/data

  nellebot-pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5444:80"
    profiles:
      - tools
    depends_on:
      - nellebot-pgsql
    environment:
      PGADMIN_DEFAULT_EMAIL: katt@bot.local
      PGADMIN_DEFAULT_PASSWORD: hunter2

volumes:
  nellebot-keydata: { }
  nellebot-pgdata: { }
    