name: Publish changelog

on:
  workflow_dispatch:

jobs:
  publish-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Get release info
        id: release-info
        uses: joutvhu/get-release@v1.0.3
        with:
          latest: true             
          debug: ${{ env.ACTIONS_RUNNER_DEBUG == 'true' }}
          throwing: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Github Release To Discord
        uses: stegzilla/discord-notify@v2
        with:
          webhook_url: ${{ secrets.RELEASE_NOTES_WEBHOOK_URL }}
          title: Reifnir updates 
          message: | 
            Release notes for update `${{ steps.release-info.outputs.name }}`
            
            ${{ steps.release-info.outputs.body }}
          colour: "23ccdc"
          avatar_url: "https://cdn.discordapp.com/avatars/827138522854981662/f0709f86c72039ef4ed55797a20a8e79.png"
          username: "Reifnir"