name: Publish release

on:
  workflow_dispatch:
      
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Github Releases To Discord
        uses: SethCohen/github-releases-to-discord@v1.13.1
        with:
          webhook_url: ${{ secrets.RELEASE_NOTES_WEBHOOK_URL }}
          color: "23ccdc"
          username: "Reifnir"
          avatar_url: "https://cdn.discordapp.com/avatars/827138522854981662/f0709f86c72039ef4ed55797a20a8e79.png"
          footer_title: "Changelog"
          footer_icon_url: "https://cdn.discordapp.com/avatars/827138522854981662/f0709f86c72039ef4ed55797a20a8e79.png"
          footer_timestamp: true