name: Release

on:
  workflow_dispatch:
    inputs:
      updateDatabase:
        description: 'Update database (allowed values: no, auto, manual)'
        required: false
        default: 'no'
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Replace tokens in appsettings
      uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: '__'
        tokenSuffix: '__'
        files: 'Nellebot/appsettings.json'
      env:
        CONNECTION_STRING: ${{secrets.DB_CONNECTION_STRING}}
        BOT_TOKEN: ${{secrets.BOT_TOKEN}}
        ORDBOK_API_KEY: ${{secrets.ORDBOK_API_KEY}}
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Test
      run: dotnet test
    
    - name: Publish
      run: dotnet publish -c Release -r linux-x64 -o deploy --no-self-contained ./Nellebot/

    - name: Generate database migration script
      if: github.event.inputs.updateDatabase == 'auto' || github.event.inputs.updateDatabase == 'manual'
      run: |
        dotnet tool install --global dotnet-ef
        dotnet tool restore
        dotnet ef migrations script --idempotent -p Nellebot.Data.Migrations -o deploy/database_migration.sql
      env:
        DOTNET_ENVIRONMENT: Production
    
    - name: Copy files to remote dir
      uses: appleboy/scp-action@master
      with:  
        host: ${{secrets.VPS_HOST}}
        port: ${{secrets.VPS_PORT}}
        username: ${{secrets.VPS_USER}}
        password: ${{secrets.VPS_PASSWORD}}        
        source: "/home/runner/work/reifnir-bot/reifnir-bot/deploy/"
        target: "/home/nellebot-user/nellebot-deploy"
        rm: true
    
    - name: Deploy - Stop service
      uses: appleboy/ssh-action@master
      with:  
        host: ${{secrets.VPS_HOST}}
        port: ${{secrets.VPS_PORT}}
        username: ${{secrets.NELLEBOT_USER}}
        password: ${{secrets.NELLEBOT_PASSWORD}}      
        script: systemctl --user stop nellebot
    
    - name: Deploy - Run deploy script
      uses: appleboy/ssh-action@master
      with:  
        host: ${{secrets.VPS_HOST}}
        port: ${{secrets.VPS_PORT}}
        username: ${{secrets.VPS_USER}}
        password: ${{secrets.VPS_PASSWORD}}      
        script: sudo /home/nellebot-user/nellebot-deploy.sh
 
    - name: Deploy - Change Nellebot permission
      uses: appleboy/ssh-action@master
      with:  
        host: ${{secrets.VPS_HOST}}
        port: ${{secrets.VPS_PORT}}
        username: ${{secrets.VPS_USER}}
        password: ${{secrets.VPS_PASSWORD}}      
        script: sudo chmod 777 /home/nellebot-user/nellebot/Nellebot

    - name: Deploy - Backup database
      if: github.event.inputs.updateDatabase == 'auto' || github.event.inputs.updateDatabase == 'manual'
      uses: appleboy/ssh-action@master
      with:  
        host: ${{secrets.VPS_HOST}}
        port: ${{secrets.VPS_PORT}}
        username: ${{secrets.VPS_USER}}
        password: ${{secrets.VPS_PASSWORD}}      
        script: sudo /home/nellebot-user/nellebot-backup-db.sh
 
    - name: Deploy - Run database migration script
      if: github.event.inputs.updateDatabase == 'auto'
      uses: appleboy/ssh-action@master
      with:  
        host: ${{secrets.VPS_HOST}}
        port: ${{secrets.VPS_PORT}}
        username: ${{secrets.VPS_USER}}
        password: ${{secrets.VPS_PASSWORD}}      
        script: sudo psql -U postgres -d nellebot -q -f /home/nellebot-user/nellebot/database_migration.sql
 
    - name: Deploy - Start service
      if: github.event.inputs.updateDatabase == 'no' || github.event.inputs.updateDatabase == 'auto'
      uses: appleboy/ssh-action@master
      with:  
        host: ${{secrets.VPS_HOST}}
        port: ${{secrets.VPS_PORT}}
        username: ${{secrets.NELLEBOT_USER}}
        password: ${{secrets.NELLEBOT_PASSWORD}}      
        script: systemctl --user start nellebot
